sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - autotools-dev
      - bc
      - bison
      - build-essential
      - curl
      - flex
      - gawk
      - gperf
      - libgmp-dev
      - libmpc-dev
      - libmpfr-dev
      - libtool
      - patchutils
      - texinfo
      - gcc-4.8
      - g++-4.8
before_install:
  - export MAKEFLAGS="-j3"
  - export CXX=g++-4.8
  - export CC=gcc-4.8
env:
  - CARGS="--enable-linux  --enable-multilib"
  - CARGS="--enable-linux  --disable-multilib --with-arch=rv32imac --with-abi=ilp32"
  - CARGS="--disable-linux --enable-multilib"
  - CARGS="--disable-linux --disable-multilib --with-arch=rv64gc --with-abi=lp64"
  - CARGS="--disable-linux --disable-multilib --with-arch=rv32i  --with-abi=ilp32"
install: true
script:
  - ./configure --prefix=/tmp/build-default $CARGS
  - travis_wait 90 scripts/wrapper/make_tail
  - travis_wait 45 scripts/wrapper/make_tail check
  - make report
